name: Build with MakefileGenerator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate Makefile
        run: python ./MakefileGenerator.py

      - name: show Makefile
        run: cat Makefile

      - name: Run make
        run: make
